name: Development pipeline

on:
  push:
    branches:
      - 'dev'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN_DEV }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -e ".[local,test]"

      - name: Run unit tests
        run: |
          echo "Launching unit tests"

      - name: Model development (assets only upload)
        run: |
          dbx deploy Model-develop --assets-only

      - name: Run the workflow in a jobless fashion
        run: |
          dbx launch Model-develop --from-assets --trace


