name: Production pipeline

on:
  push:
    branches:
      - 'prod'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
 ci-pipeline:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 4

      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
        DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN_PROD }}

      steps:
        - uses: actions/checkout@v1

        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
            cache-dependency-path: setup.py

        - name: Install pip
          run: |
            python -m pip install --upgrade pip

        - name: Install dependencies and project in dev mode
          run: |
            pip install -e ".[local,test]"

        - name: Run unit tests
          run: |
            echo "Launching unit tests"

        - name: Model development (assets only upload)
          run: |
            dbx deploy Model-develop --assets-only

        - name: Run the workflow in a jobless fashion
          run: |
            dbx launch Model-develop --from-assets --trace

        - name: Delete Databricks Secrets Scope
          run: |
            databricks secrets delete-scope --scope secrets-scope

        - name: Create Databricks Secrets Scope
          run: |
            databricks secrets create-scope --scope secrets-scope
            

        - name: Set Databricks Secrets
          run: |
            databricks secrets put --scope secrets-scope --key aws-access-key --string-value "${{ secrets.AWS_ACCESS_KEY }}"
            databricks secrets put --scope secrets-scope --key aws-secret-key --string-value "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            databricks secrets put --scope secrets-scope --key databricks-host --string-value "${{ secrets.DATABRICKS_HOST }}"
            databricks secrets put --scope secrets-scope --key databricks-token --string-value "${{ secrets.DATABRICKS_TOKEN }}"

            
        - name: Workflow Data-preprocessing deployment (assets only upload)
          run: |
            dbx deploy Data-preprocessing --assets-only 

        - name: Run the Data-preprocessing workflow in a jobless fashion
          run: |
            dbx launch Data-preprocessing --from-assets --trace 

        - name: Workflow Model-Training deployment (assets only upload)
          run: |
            dbx deploy Model-Training --assets-only 

        - name: Run the Model-Training workflow in a jobless fashion
          run: |
            dbx launch Model-Training --from-assets --trace 

        # - name: Workflow Model-Inferencing deployment (assets only upload)
        #   run: |
        #     dbx deploy Model-Inferencing --assets-only 

        # - name: Run the Model-Inferencing workflow in a jobless fashion
        #   run: |
        #     dbx launch Model-Inferencing --from-assets --trace 

        - name: Workflow Mlflow Webhook deployment (assets only upload)
          run: |
            dbx deploy Data-Drift --assets-only 

        - name: Run the Mlflow Webhook workflow in a jobless fashion
          run: |
            dbx launch Data-Drift --from-assets --trace 
      

        - name: Workflow deployment (assets only upload)
          run: |
            dbx deploy Prod-stag --assets-only

        - name: Run the workflow in a jobless fashion
          run: |
            dbx launch Prod-stag --from-assets --trace


